# Generated by Django 4.1.1 on 2022-09-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
